pipeline {
    agent any

    tools {
            NodeJS 'NodeJS' // Use the name of the Node.js installation configured in Jenkins Global Tool Configuration
        }

    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    // Install Node.js dependencies (like newman)
                    sh 'npm install'
                }
            }
        }

        stage('Run Newman Tests') {
            steps {
                script {
                    // Run the Newman collection using the runner.js script
                    sh 'node runner.js'
                }
            }
        }

        stage('Archive Test Results') {
            steps {
                script {
                    // Archive the HTML report generated by the Newman test run
                    archiveArtifacts artifacts: 'htmlResults.html', allowEmptyArchive: true
                }
            }
        }
    }

    post {
        always {
            // Always clean up the workspace after the pipeline is done
            cleanWs()
        }
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
